spring:
  datasource:
    url: jdbc:mysql://localhost:3307/taskhup
    username: root
    password: example_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  profiles:
#    active: h2
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nviethung0902@gmail.com
    password: nwspwvnmwkpoltyz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    com.taskhub.project.aspect.LoggingAspect: DEBUG
#    root: debug

springdoc:
  swagger-ui:
    path: /swagger
    csrf:
      enabled: true

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  fe-uri: http://localhost:5173/
  base-uri: http://localhost:8080/
  name: task-hub
  jwt-secret: 413F4428472B4B6250645367566B5970337336763979244226452948404D6351
#  jwt-expiration-ms: 3000  #3 second  #60000 #1 min
#  jwt-refresh-expiration-ms: 120000 #2 min
  jwt-expiration-ms: 3600000
  jwt-refresh-expiration-ms: 86400000
  jwt-alg: HS256 #RSA #HS256
  rsa-key-length: 2048

  cloud:
    cloudinary:
        cloud-name: dhqx90jaa
        api-key: 451868283958682
        api-secret: VIK9IqlWmda8a68dUyEqwcbbmzU

  auth:
    white-list: >
      /actuator/**,
      /api/v1/auth/**,
      /ws-endpoint/**,
      /swagger,
      /v2/api-docs,
      /swagger-ui.html,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /webjars/**,
      /v3/api-docs/**,
      /swagger-ui/**,
      /api/v1/file/**
    auth-list: >
      /api/v1/workspaces/**